In [39]:
import pandas as pd 

df = pd.read_csv('1_dados_brutos/datatran2023.csv', sep=';', encoding='latin1')

df.head()

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,496519,2023-01-01,domingo,02:00:00,ES,101,114,SOORETAMA,Ausência de reação do condutor,Saída de leito carroçável,...,0,0,0,1,1,"-19,09484877","-40,05095848",SPRF-ES,DEL04-ES,UOP01-DEL04-ES
1,496543,2023-01-01,domingo,03:40:00,SP,116,"113,1",TAUBATE,Entrada inopinada do pedestre,Atropelamento de Pedestre,...,0,0,4,0,2,"-23,0445658","-45,58259814",SPRF-SP,DEL02-SP,UOP02-DEL02-SP
2,496590,2023-01-01,domingo,01:40:00,MT,163,1112,GUARANTA DO NORTE,Reação tardia ou ineficiente do condutor,Tombamento,...,1,0,2,1,3,"-9,70020602","-54,87588757",SPRF-MT,DEL06-MT,UOP03-DEL06-MT
3,496610,2023-01-01,domingo,10:40:00,PR,376,"314,8",ORTIGUEIRA,Velocidade Incompatível,Tombamento,...,0,1,2,0,3,"-23,985512","-51,083555",SPRF-PR,DEL07-PR,UOP02-DEL07-PR
4,496659,2023-01-01,domingo,14:55:00,MG,116,"569,4",MANHUACU,Acumulo de água sobre o pavimento,Colisão frontal,...,2,1,1,2,3,"-20,10007457","-42,17884091",SPRF-MG,DEL06-MG,UOP03-DEL06-MG

In [104]:
linhas_nulas = df[df.isna().any(axis=1)]

# Mostrar as linhas que possuem valores nulos
print(linhas_nulas)

           id data_inversa     dia_semana   horario  uf   br     km  \
2      496590   2023-01-01        domingo  01:40:00  MT  163   1112
549    499508   2023-01-16  segunda-feira  10:00:00  DF    0      0
1844   505418   2023-01-04   quarta-feira  10:40:00  DF    0      0
4333   516377   2023-04-12   quarta-feira  08:05:00  DF    0      0
7251   529454   2023-06-10         sábado  13:10:00  BA    0      0
12310  550686   2023-09-20   quarta-feira  22:00:00  PA    0      0
14362  558905   2023-11-03    sexta-feira  16:40:00  AL    0      0
17589  616125   2023-05-20         sábado  13:45:00  CE    0      0
17590  616819   2023-01-24    terça-feira  15:20:00  RJ  101  308,4
17591  619762   2023-11-08   quarta-feira  06:40:00  BA  242    244
17592  619871   2023-12-13   quarta-feira  06:50:00  SC  101  215,8
21902  502783   2023-02-03    sexta-feira  06:50:00  PE    0      0
22502  503702   2023-01-27    sexta-feira  09:20:00  PI    0      0
22798  504221   2023-02-09   quinta-feira  16:30:00  MS    0      0
23275  504928   2023-01-28         sábado  10:00:00  MA    0      0
23475  505249   2023-02-10    sexta-feira  16:10:00  DF    0      0
24395  506631   2023-02-22   quarta-feira  12:00:00  BA    0      0
27669  511819   2023-03-17    sexta-feira  18:30:00  RS    0      0
28094  512543   2023-03-23   quinta-feira  09:50:00  BA    0      0
33820  521162   2023-02-06  segunda-feira  14:50:00  AM    0      0
33851  521211   2023-04-27   quinta-feira  16:00:00  RS    0      0
34292  521840   2023-04-22         sábado  16:30:00  RR    0      0
34589  522319   2023-05-09    terça-feira  14:15:00  MG    0      0
38947  528822   2023-06-11        domingo  15:00:00  PA    0      0
40410  531069   2023-06-22   quinta-feira  11:00:00  SC    0      0
42134  533682   2023-07-04    terça-feira  17:40:00  DF    0      0
42821  534749   2023-07-09        domingo  12:30:00  MS    0      0
45442  538697   2023-07-28    sexta-feira  14:00:00  DF    0      0
47123  541279   2023-08-02   quarta-feira  14:40:00  RS    0      0
47844  542340   2023-08-14  segunda-feira  09:30:00  DF    0      0
52486  549447   2023-06-19  segunda-feira  07:30:00  MA    0      0
55300  553846   2023-10-03    terça-feira  12:35:00  PA    0      0
56653  555939   2023-10-19   quinta-feira  09:00:00  AM    0      0
64096  567249   2023-11-09   quinta-feira  18:30:00  PE    0      0
64121  567284   2023-10-10    terça-feira  15:00:00  PA    0      0
64177  567364   2023-12-08    sexta-feira  20:46:00  RO    0      0
65361  569136   2023-12-18  segunda-feira  13:20:00  MT    0      0
67743  610394   2023-12-06   quarta-feira  17:15:00  RJ    0      0
67757  616314   2023-06-19  segunda-feira  07:00:00  SP  116  206,5
67758  616532   2023-02-19        domingo  10:58:00  RO  429     49
67759  616562   2023-06-07   quarta-feira  21:50:00  MG  364     26
67760  617175   2023-09-24        domingo  05:00:00  SC  470    0,9
67761  619297   2023-04-19   quarta-feira  20:50:00  PR  376    475
67762  619475   2023-06-20    terça-feira  20:30:00  MA  222  206,5
67763  619476   2023-05-18   quinta-feira  06:15:00  ES  101   62,7
67764  619913   2023-08-22    terça-feira  15:00:00  MG   50     15
67765  620943   2023-08-14  segunda-feira  13:30:00  RJ  116    148

                municipio                                     causa_acidente  \
2       GUARANTA DO NORTE           Reação tardia ou ineficiente do condutor
549              BRASILIA                        Manobra de mudança de faixa
1844             BRASILIA                                   Obstrução na via
4333             BRASILIA           Reação tardia ou ineficiente do condutor
7251              SANTANA           Reação tardia ou ineficiente do condutor
12310    VITORIA DO XINGU                               Problema com o freio
14362     TEOTONIO VILELA  Condutor deixou de manter distância do veículo...
17589         MORADA NOVA           Reação tardia ou ineficiente do condutor
17590         SAO GONCALO                     Ausência de reação do condutor
17591           ITABERABA                            Velocidade Incompatível
17592             PALHOCA  Condutor deixou de manter distância do veículo...
21902              RECIFE     Acumulo de areia ou detritos sobre o pavimento
22502            TERESINA           Objeto estático sobre o leito carroçável
22798        CAMPO GRANDE                                 Pista Escorregadia
23275            SAO LUIS                            Ausência de sinalização
23475            BRASILIA                        Manobra de mudança de faixa
24395            SALVADOR           Reação tardia ou ineficiente do condutor
27669             LAJEADO  Acessar a via sem observar a presença dos outr...
28094            SALVADOR  Acessar a via sem observar a presença dos outr...
33820              MANAUS           Reação tardia ou ineficiente do condutor
33851        SAO LEOPOLDO                                  Frear bruscamente
34292             IRACEMA                                 Pista Escorregadia
34589        JUIZ DE FORA               Demais falhas mecânicas ou elétricas
38947   GARRAFAO DO NORTE           Objeto estático sobre o leito carroçável
40410       FLORIANOPOLIS           Reação tardia ou ineficiente do condutor
42134            BRASILIA                             Transitar na contramão
42821        CAMPO GRANDE  Condutor deixou de manter distância do veículo...
45442            BRASILIA  Acessar a via sem observar a presença dos outr...
47123         FARROUPILHA                                  Frear bruscamente
47844            BRASILIA              Estacionar ou parar em local proibido
52486            SAO LUIS                                 Pista Escorregadia
55300               BELEM           Reação tardia ou ineficiente do condutor
56653              MANAUS                             Transitar na contramão
64096              RECIFE                              Iluminação deficiente
64121  SAO FELIX DO XINGU               Demais falhas mecânicas ou elétricas
64177           ARIQUEMES                               Transitar na calçada
65361              CUIABA                     Ausência de reação do condutor
67743      RIO DE JANEIRO              Afundamento ou ondulação no pavimento
67757           GUARULHOS                                   Retorno proibido
67758   PRESIDENTE MEDICI                                   Pista esburacada
67759              FRUTAL                             Ultrapassagem Indevida
67760              GASPAR                     Ausência de reação do condutor
67761        PONTA GROSSA                           Pedestre andava na pista
67762     ITAPECURU MIRIM  Acessar a via sem observar a presença dos outr...
67763          SAO MATEUS                                 Conversão proibida
67764          UBERLANDIA     Acumulo de areia ou detritos sobre o pavimento
67765     DUQUE DE CAXIAS                                              Chuva

                        tipo_acidente  ... feridos_graves ilesos ignorados  \
2                          Tombamento  ...              1      0         2
549     Colisão lateral mesmo sentido  ...              0      4         1
1844               Colisão com objeto  ...              0      1         0
4333                 Colisão traseira  ...              0      2         0
7251   Colisão lateral sentido oposto  ...              0      2         1
12310             Colisão transversal  ...              0      1         1
14362                Colisão traseira  ...              0      1         0
17589  Colisão lateral sentido oposto  ...              0      2         0
17590                Colisão traseira  ...              0      1         2
17591                      Tombamento  ...              1      0         2
17592   Colisão lateral mesmo sentido  ...              1      1         0
21902    Queda de ocupante de veículo  ...              0      0         0
22502              Colisão com objeto  ...              0      3         0
22798       Saída de leito carroçável  ...              0      2         0
23275                 Colisão frontal  ...              0      2         0
23475             Colisão transversal  ...              0      2         0
24395                Colisão traseira  ...              0      2         0
27669             Colisão transversal  ...              0      1         0
28094                      Tombamento  ...              1      0         0
33820   Colisão lateral mesmo sentido  ...              0      4         0
33851                Colisão traseira  ...              0      7         0
34292   Colisão lateral mesmo sentido  ...              0      5         0
34589                Eventos atípicos  ...              0      2         0
38947              Colisão com objeto  ...              0      7         1
40410                     Capotamento  ...              0      3         0
42134                 Colisão frontal  ...              0      4         0
42821   Colisão lateral mesmo sentido  ...              0      3         0
45442   Colisão lateral mesmo sentido  ...              0      1         0
47123              Colisão com objeto  ...              0      3         0
47844                Colisão traseira  ...              0      6         1
52486                Colisão traseira  ...              0      2         0
55300             Colisão transversal  ...              0      4         0
56653             Colisão transversal  ...              0      2         0
64096              Colisão com objeto  ...              0      1         0
64121              Colisão com objeto  ...              0      3         0
64177              Colisão com objeto  ...              0      2         0
65361   Colisão lateral mesmo sentido  ...              0      1         1
67743              Colisão com objeto  ...              0      0         6
67757                 Colisão frontal  ...              0      1         0
67758                     Capotamento  ...              1      0         0
67759   Colisão lateral mesmo sentido  ...              1      1         0
67760                 Colisão frontal  ...              2      0         0
67761       Atropelamento de Pedestre  ...              0      4         0
67762             Colisão transversal  ...              0      1         0
67763             Colisão transversal  ...              1      0         0
67764                      Tombamento  ...              1      0         0
67765    Queda de ocupante de veículo  ...              0      0         0

      feridos veiculos      latitude     longitude  regional  delegacia  \
2           1        3   -9,70020602  -54,87588757   SPRF-MT   DEL06-MT
549         0        4     -15,81589    -47,949594       NaN        NaN
1844        0        1  -15,81581596  -47,94698412   SPRF-DF        NaN
4333        0        2    -15,739533     -47,89059       NaN        NaN
7251        0        3           -13           -44   SPRF-BA   DEL10-BA
12310       0        2     -3,065758    -52,000226   SPRF-PA   DEL04-PA
14362       3        4   -9,90997737  -36,33571386   SPRF-AL   DEL02-AL
17589       0        2   -4,83723993  -38,39910507       NaN        NaN
17590       1        4  -22,79309326  -43,02479595       NaN        NaN
17591       1        3    -12,501019    -40,427317       NaN        NaN
17592       1        2  -27,65237092  -48,67664337       NaN        NaN
21902       1        1    -8,0756735  -34,94560003   SPRF-PE   DEL01-PE
22502       0        1   -5,09534333  -42,78653568   SPRF-PI   DEL01-PI
22798       0        1    -20,580711    -54,675145   SPRF-MS   DEL01-MS
23275       1        2   -2,60917577  -44,25572103   SPRF-MA        NaN
23475       0        2    -15,800412    -47,967913       NaN        NaN
24395       0        2    -12,978042    -38,463161   SPRF-BA        NaN
27669       2        2     -29,46643    -51,955135   SPRF-RS   DEL04-RS
28094       2        2  -12,92239928  -38,46071005   SPRF-BA        NaN
33820       0        2   -3,08563339  -60,03029466   SPRF-AM        NaN
33851       0        2  -29,79453087  -51,16207665   SPRF-RS   DEL01-RS
34292       0        2    2,30120456  -61,25124156   SPRF-RR        NaN
34589       0        1    -21,793183    -43,384245   SPRF-MG   DEL05-MG
38947       2        5     -2,035506    -46,988998   SPRF-PA        NaN
40410       0        1  -27,43678397  -48,45500708    UniPRF        NaN
42134       0        2  -15,80227216  -47,97075218   SPRF-DF        NaN
42821       1        2    -20,453018    -54,647419   SPRF-MS   DEL01-MS
45442       1        2    -15,804265    -47,957914   SPRF-DF        NaN
47123       0        1  -29,22906705  -51,34184014   SPRF-RS   DEL06-RS
47844       0        4  -15,83299522  -47,92371082       NaN        NaN
52486       0        2   -2,49096464  -44,23458153   SPRF-MA   DEL01-MA
55300       0        2     -1,308115    -48,459827   SPRF-PA        NaN
56653       0        2     -3,067371    -60,003822   SPRF-AM        NaN
64096       0        1   -8,11443984  -34,89817357   SPRF-PE        NaN
64121       0        1   -5,74819887  -52,04073821   SPRF-PA   DEL03-PA
64177       0        2   -9,92399025  -63,03749453   SPRF-RO   DEL03-RO
65361       0        2  -15,60592558  -56,10406637   SPRF-MT        NaN
67743       0        2       -22,862      -43,2369   SPRF-RJ        NaN
67757       1        2  -23,41932833  -46,38385848       NaN        NaN
67758       2        1  -11,20008199    -61,973129       NaN        NaN
67759       1        2  -20,03237481  -48,87622118       NaN        NaN
67760       3        2  -26,92203838  -48,95884931       NaN        NaN
67761       0        2  -25,05467785  -50,22938892       NaN        NaN
67762       1        2   -3,40552588  -44,35174989       NaN        NaN
67763       3        2  -18,69020499  -39,86154403       NaN        NaN
67764       1        1  -18,91385522  -48,17243636       NaN        NaN
67765       1        1   -22,6723488  -43,28215398       NaN        NaN

                  uop
2      UOP03-DEL06-MT
549               NaN
1844              NaN
4333              NaN
7251              NaN
12310             NaN
14362             NaN
17589             NaN
17590             NaN
17591             NaN
17592             NaN
21902             NaN
22502             NaN
22798             NaN
23275             NaN
23475             NaN
24395             NaN
27669             NaN
28094             NaN
33820             NaN
33851             NaN
34292             NaN
34589             NaN
38947             NaN
40410             NaN
42134             NaN
42821             NaN
45442             NaN
47123             NaN
47844             NaN
52486             NaN
55300             NaN
56653             NaN
64096             NaN
64121             NaN
64177             NaN
65361             NaN
67743             NaN
67757             NaN
67758             NaN
67759             NaN
67760             NaN
67761             NaN
67762             NaN
67763             NaN
67764             NaN
67765             NaN

[47 rows x 30 columns]

In [ ]:
import os

pasta_dados = '1_dados_brutos'
lista_dfs = []

# Mapeia e lê cada arquivo CSV da pasta
for arquivo in os.listdir(pasta_dados):
    if arquivo.endswith('.csv'):
        caminho_completo = os.path.join(pasta_dados, arquivo)
        df_temp = pd.read_csv(caminho_completo, sep=';', encoding='latin1')
        lista_dfs.append(df_temp)

# Concatena todas as tabelas em um único DataFrame
df_prf = pd.concat(lista_dfs, ignore_index=True)

df_prf

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,496519.0,2023-01-01,domingo,02:00:00,ES,101,114,SOORETAMA,Ausência de reação do condutor,Saída de leito carroçável,...,0,0,0,1,1,"-19,09484877","-40,05095848",SPRF-ES,DEL04-ES,UOP01-DEL04-ES
1,496543.0,2023-01-01,domingo,03:40:00,SP,116,"113,1",TAUBATE,Entrada inopinada do pedestre,Atropelamento de Pedestre,...,0,0,4,0,2,"-23,0445658","-45,58259814",SPRF-SP,DEL02-SP,UOP02-DEL02-SP
2,496590.0,2023-01-01,domingo,01:40:00,MT,163,1112,GUARANTA DO NORTE,Reação tardia ou ineficiente do condutor,Tombamento,...,1,0,2,1,3,"-9,70020602","-54,87588757",SPRF-MT,DEL06-MT,UOP03-DEL06-MT
3,496610.0,2023-01-01,domingo,10:40:00,PR,376,"314,8",ORTIGUEIRA,Velocidade Incompatível,Tombamento,...,0,1,2,0,3,"-23,985512","-51,083555",SPRF-PR,DEL07-PR,UOP02-DEL07-PR
4,496659.0,2023-01-01,domingo,14:55:00,MG,116,"569,4",MANHUACU,Acumulo de água sobre o pavimento,Colisão frontal,...,2,1,1,2,3,"-20,10007457","-42,17884091",SPRF-MG,DEL06-MG,UOP03-DEL06-MG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243220,778107.0,01/02/2026,domingo,11:00:00,PR,476,"104,5",COLOMBO,Reação tardia ou ineficiente do condutor,Tombamento,...,1,0,0,1,1,"-25,27260195","-49,14000034",NaN,NaN,NaN
243221,778123.0,15/05/2026,sexta-feira,23:00:00,RJ,393,181,PARAIBA DO SUL,Animais na Pista,Atropelamento de Animal,...,0,0,0,3,1,"-22,1431633","-43,2762383",NaN,NaN,NaN
243222,778324.0,12/05/2026,terça-feira,06:20:00,MG,40,"0,9",PARACATU,Velocidade Incompatível,Saída de leito carroçável,...,1,0,0,1,1,"-17,037917","-47,153178",NaN,NaN,NaN
243223,778325.0,20/05/2026,quarta-feira,18:03:00,MT,364,"269,8",JACIARA,Acessar a via sem observar a presença dos outr...,Colisão frontal,...,3,0,0,3,2,"-15,968958","-54,943692",NaN,NaN,NaN
243224,778326.0,28/05/2026,quinta-feira,18:07:00,PR,280,"314,7",BARRACAO,Reação tardia ou ineficiente do condutor,Colisão traseira,...,1,1,0,1,2,"-26,29215493","-53,53091598",NaN,NaN,NaN

In [42]:
df_prf.info()

<class 'pandas.DataFrame'>
RangeIndex: 243225 entries, 0 to 243224
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      243225 non-null  float64
 1   data_inversa            243225 non-null  str
 2   dia_semana              243225 non-null  str
 3   horario                 243225 non-null  str
 4   uf                      243225 non-null  str
 5   br                      243225 non-null  int64
 6   km                      243225 non-null  str
 7   municipio               243225 non-null  str
 8   causa_acidente          243225 non-null  str
 9   tipo_acidente           243225 non-null  str
 10  classificacao_acidente  243221 non-null  str
 11  fase_dia                243225 non-null  str
 12  sentido_via             243225 non-null  str
 13  condicao_metereologica  243225 non-null  str
 14  tipo_pista              243225 non-null  str
 15  tracado_via             243225 non-null  str
 16  uso_solo                243225 non-null  str
 17  pessoas                 243225 non-null  int64
 18  mortos                  243225 non-null  int64
 19  feridos_leves           243225 non-null  int64
 20  feridos_graves          243225 non-null  int64
 21  ilesos                  243225 non-null  int64
 22  ignorados               243225 non-null  int64
 23  feridos                 243225 non-null  int64
 24  veiculos                243225 non-null  int64
 25  latitude                243225 non-null  object
 26  longitude               243225 non-null  object
 27  regional                243186 non-null  str
 28  delegacia               243111 non-null  str
 29  uop                     242996 non-null  str
dtypes: float64(1), int64(9), object(2), str(18)
memory usage: 55.7+ MB

In [43]:

pasta_dados = '1_dados_brutos'

# Dicionário para guardar as colunas de cada arquivo
colunas_por_arquivo = {}

for arquivo in sorted(os.listdir(pasta_dados)):
    if arquivo.endswith('.csv'):
        caminho = os.path.join(pasta_dados, arquivo)
        # Lê apenas 1 linha para carregar só o cabeçalho rápido
        df_temp = pd.read_csv(caminho, sep=';', encoding='latin1', nrows=1)
        colunas_por_arquivo[arquivo] = list(df_temp.columns)

# Compara a quantidade de colunas em cada arquivo
for arquivo, cols in colunas_por_arquivo.items():
    print(f'{arquivo}: {len(cols)} colunas')

datatran2023.csv: 30 colunas
datatran2024.csv: 30 colunas
datatran2025.csv: 30 colunas
datatran2026.csv: 30 colunas

In [44]:
# 1. Conta o total de nulos e calcula a porcentagem por coluna
nulos_qtd = df_prf.isna().sum()
nulos_pct = (df_prf.isna().mean() * 100).round(2)

# 2. Consolida em uma tabela, filtra apenas quem tem nulos e ordena do maior para o menor
relatorio_nulos = (
    pd.DataFrame({'Qtd_Nulos': nulos_qtd, 'Porcentagem_%': nulos_pct})
    .query('Qtd_Nulos > 0')
    .sort_values(by='Qtd_Nulos', ascending=False)
)

relatorio_nulos

                        Qtd_Nulos  Porcentagem_%
uop                           229           0.09
delegacia                     114           0.05
regional                       39           0.02
classificacao_acidente          4           0.00

In [45]:
# Trata os valores nulos preenchendo com 'Não Informado'
colunas_nulas = ['uop', 'delegacia', 'regional', 'classificacao_acidente']
df_prf[colunas_nulas] = df_prf[colunas_nulas].fillna('Não Informado')

# Checa se existem linhas 100% duplicadas na base unificada
total_duplicadas = df_prf.duplicated().sum()
print(f"Total de linhas duplicadas: {total_duplicadas}")

Total de linhas duplicadas: 0

In [46]:
import sqlite3
# Conecta/cria o banco de dados diretamente na pasta 2_banco_de_dados

conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')

# Salva a base limpa do Pandas como uma tabela chamada 'tb_acidentes'
df_prf.to_sql('tb_acidentes', conexao, if_exists='replace', index=False)

print("Tabela 'tb_acidentes' criada com sucesso no seu Banco SQL!")

Tabela 'tb_acidentes' criada com sucesso no seu Banco SQL!

In [47]:
# Consulta as 5 primeiras linhas direto do Banco de Dados usando SQL
df_teste = pd.read_sql_query("SELECT * FROM tb_acidentes LIMIT 5;", conexao)
df_teste

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,496519.0,2023-01-01,domingo,02:00:00,ES,101,114,SOORETAMA,Ausência de reação do condutor,Saída de leito carroçável,...,0,0,0,1,1,"-19,09484877","-40,05095848",SPRF-ES,DEL04-ES,UOP01-DEL04-ES
1,496543.0,2023-01-01,domingo,03:40:00,SP,116,"113,1",TAUBATE,Entrada inopinada do pedestre,Atropelamento de Pedestre,...,0,0,4,0,2,"-23,0445658","-45,58259814",SPRF-SP,DEL02-SP,UOP02-DEL02-SP
2,496590.0,2023-01-01,domingo,01:40:00,MT,163,1112,GUARANTA DO NORTE,Reação tardia ou ineficiente do condutor,Tombamento,...,1,0,2,1,3,"-9,70020602","-54,87588757",SPRF-MT,DEL06-MT,UOP03-DEL06-MT
3,496610.0,2023-01-01,domingo,10:40:00,PR,376,"314,8",ORTIGUEIRA,Velocidade Incompatível,Tombamento,...,0,1,2,0,3,"-23,985512","-51,083555",SPRF-PR,DEL07-PR,UOP02-DEL07-PR
4,496659.0,2023-01-01,domingo,14:55:00,MG,116,"569,4",MANHUACU,Acumulo de água sobre o pavimento,Colisão frontal,...,2,1,1,2,3,"-20,10007457","-42,17884091",SPRF-MG,DEL06-MG,UOP03-DEL06-MG

In [ ]:
import sqlite3


# 1. Abre uma nova conexão com o arquivo do banco
conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')

try:
    # 2. Envia a base bruta do Pandas para o SQLite
    df_prf.to_sql('tb_acidentes_bruto', conexao, if_exists='replace', index=False)
    
    # 3. Prepara e executa a criação da tabela filtrada
    cursor = conexao.cursor()
    cursor.execute("DROP TABLE IF EXISTS tb_acidentes_limpo;")
    
    query_criar_tabela = """
    CREATE TABLE tb_acidentes_limpo AS
    SELECT 
        id,
        data_inversa,
        dia_semana,
        horario,
        uf,
        br,
        km,
        municipio,
        causa_acidente,
        tipo_acidente,
        classificacao_acidente,
        fase_dia,
        sentido_via,
        condicao_metereologica,
        tipo_pista,
        tracado_via,
        uso_solo,
        pessoas,
        mortos,
        feridos_graves,
        feridos_leves,
        ilesos,
        feridos,
        veiculos,
        latitude,
        longitude
    FROM tb_acidentes_bruto;
    """
    cursor.execute(query_criar_tabela)
    conexao.commit()
    
    # 4. Lê as primeiras linhas para confirmar que a tabela foi criada
    df_teste = pd.read_sql_query("SELECT * FROM tb_acidentes_limpo LIMIT 5;", conexao)
    print("Tabela 'tb_acidentes_limpo' criada e validada com sucesso!")

finally:
    # 5. Garante o fechamento da conexão só no fim da execução
    conexao.close()

df_teste

In [79]:
conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')

# Analisar qual a quantidade de sinistros por UF.  
# Embora São Paulo seja o estado mais populoso e com a maior frota do país,
# ele aparece em 6º lugar neste dataset.
# Isso ocorre porque a base de dados analisa exclusivamente rodovias federais (BRs).
# A malha rodoviária paulista é composta majoritariamente por rodovias estaduais (SPs)
# cujos sinistros são registrados pelo governo estadual (Infosiga/DER) e não pela PRF."

qtd_sinistros_uf =pd.read_sql_query('''SELECT COUNT(id) AS total_sinistros, uf FROM tb_acidentes 
GROUP BY uf ORDER BY total_sinistros DESC''', conexao)
qtd_sinistros_uf

    total_sinistros  uf
0             31629  MG
1             27904  SC
2             25570  PR
3             21036  RJ
4             16952  RS
5             16152  SP
6             13726  BA
7             11032  GO
8             10605  PE
9              8573  MT
10             8256  ES
11             6196  PB
12             5864  MS
13             5201  RN
14             5117  RO
15             4856  PI
16             4621  CE
17             4100  MA
18             3463  DF
19             3439  PA
20             2365  TO
21             2219  AL
22             1962  SE
23              911  AC
24              535  AP
25              474  AM
26              467  RR

In [ ]:
conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')

# Analisar qual a quantidade de vítimais fatais nos sinistros por UF.
# Insight: Minas Gerais é o estado com maior número de vítimas fatais.
# O estado lidera em mortes porque possui a maior malha de estradas 
# federais do Brasil e serve de conexão central para o transporte de cargas de todo o país.

vítimas_fatais_uf = pd.read_sql_query('''SELECT uf, sum(mortos) AS vitimas_fatais FROM tb_acidentes
 GROUP BY uf ORDER BY vitimas_fatais DESC;''', conexao)

vítimas_fatais_uf

    uf  vitimas_fatais
0   MG            2614
1   BA            2016
2   PR            1987
3   SC            1380
4   RJ            1125
5   RS            1108
6   PE            1067
7   GO            1039
8   MA             902
9   MT             846
10  SP             756
11  PA             712
12  MS             575
13  ES             566
14  PI             560
15  CE             556
16  PB             459
17  RN             371
18  RO             360
19  TO             349
20  AL             294
21  SE             168
22  DF             155
23  RR              92
24  AC              81
25  AM              78
26  AP              43

In [72]:
conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')

# Analisar qual a quantidade de sinistros pelo tipo de traçado da via 
# (reta, curva, aclive, declive, etc.)


tracado_via = pd.read_sql_query(
    '''SELECT tracado_via, COUNT(id) AS total_sinistros
      FROM tb_acidentes GROUP BY tracado_via ORDER BY total_sinistros DESC;''', conexao)
tracado_via

                                            tracado_via  total_sinistros
0                                                  Reta           134862
1                                                 Curva            27882
2                                          Reta;Declive             6943
3                                           Reta;Aclive             5902
4                                    Interseção de Vias             5884
...                                                 ...              ...
1134            Aclive;Curva;Viaduto;Interseção de Vias                1
1135                                 Aclive;Curva;Túnel                1
1136  Aclive;Curva;Interseção de Vias;Viaduto;Rotatória                1
1137            Aclive;Curva;Interseção de Vias;Viaduto                1
1138           Aclive;Curva;Interseção de Vias;Em Obras                1

[1139 rows x 2 columns]

In [75]:
conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')

# Analisar qual a quantidade de sinistros pelo tipo de acidente
#  (colisão, saída de pista, atropelamento, etc.)

tipo_acidente = pd.read_sql_query(  
        '''SELECT tipo_acidente, COUNT(id) AS total_sinistros 
        FROM tb_acidentes GROUP BY tipo_acidente 
        ORDER BY total_sinistros DESC;''', conexao)
tipo_acidente

                     tipo_acidente  total_sinistros
0                 Colisão traseira            47170
1        Saída de leito carroçável            35534
2              Colisão transversal            30999
3    Colisão lateral mesmo sentido            26075
4                       Tombamento            21109
5               Colisão com objeto            17137
6                  Colisão frontal            16115
7     Queda de ocupante de veículo            11345
8        Atropelamento de Pedestre            10547
9   Colisão lateral sentido oposto             7086
10                        Incêndio             5674
11                     Capotamento             4812
12                   Engavetamento             4239
13         Atropelamento de Animal             4008
14                Eventos atípicos              987
15           Derramamento de carga              364
16    Sinistro pessoal de trânsito               24

In [ ]:
conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')

# Extrair o ano da coluna data_inversa e contar sinistros por ano
# A coluna data_inversa possui datas em formatos diferentes, como "2023-01-15" e "15/01/2023"
# por isso, usamos uma expressão CASE para extrair o ano corretamente.

sinistros_por_ano = pd.read_sql_query('''
    SELECT 
        CASE 
            WHEN data_inversa LIKE '%-%' THEN SUBSTR(data_inversa, 1, 4)
            WHEN data_inversa LIKE '%/%' THEN SUBSTR(data_inversa, 7, 4)
            ELSE NULL
        END as ano,
        COUNT(id) as total_sinistros
    FROM tb_acidentes
    WHERE data_inversa IS NOT NULL
    GROUP BY ano
    ORDER BY total_sinistros DESC;
''', conexao)

sinistros_por_ano

    ano  total_sinistros
0  2024            73156
1  2025            72529
2  2023            67766
3  2026            29774

In [ ]:
conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')

# Para analisar a quantidade de vítimas fatais por tipo de acidente,
# podemos utilizar a função SUM para somar o número de mortos em cada tipo de acidente. 
# A consulta SQL abaixo agrupa os registros pelo tipo de acidente
# e calcula a soma das vítimas fatais, ordenando o resultado em ordem decrescente.
# Podemos observar que o tipo de acidente com maior número de vítimas fatais é a colisão,
#  seguida por saída de pista, atropelamento e capotamento.


vitimas_fatais_tipo_acidente = pd.read_sql_query('''SELECT tipo_acidente, sum(mortos) AS vitimas_fatais
 FROM tb_acidentes
 GROUP BY tipo_acidente ORDER BY vitimas_fatais DESC;''', conexao)

vitimas_fatais_tipo_acidente

                     tipo_acidente  vitimas_fatais
0                  Colisão frontal            6399
1        Atropelamento de Pedestre            3102
2        Saída de leito carroçável            2329
3                 Colisão traseira            2211
4              Colisão transversal            1616
5               Colisão com objeto             998
6                       Tombamento             947
7   Colisão lateral sentido oposto             792
8    Colisão lateral mesmo sentido             747
9     Queda de ocupante de veículo             356
10         Atropelamento de Animal             280
11                     Capotamento             208
12                   Engavetamento             167
13                Eventos atípicos              87
14           Derramamento de carga               9
15    Sinistro pessoal de trânsito               6
16                        Incêndio               5

In [ ]:
conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')

#N Analisar qual a quantidade de sinistros por fase do dia (manhã, tarde, noite, madrugada)
# Insight: A fase do dia com maior número de sinistros é a tarde, seguida pela manhã, 
# noite e madrugada.

sinistros_por_fase_dia = pd.read_sql_query('''SELECT fase_dia, COUNT(id) AS total_sinistros
 FROM tb_acidentes  GROUP BY fase_dia ORDER BY total_sinistros DESC;''', conexao)           
sinistros_por_fase_dia

      fase_dia  total_sinistros
0    Pleno dia           134735
1  Plena Noite            83636
2    Anoitecer            13186
3    Amanhecer            11668

In [92]:
conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')

# Podemos observar que algumas das maiores quantidades de sinistros 
# ocorrem em datas específicas do ano, 
# especialmente em dezembro, possivelmente devido ao aumento do fluxo
# de veículos nas rodovias federais durante o período de férias e festas de fim de ano.
# Outubro teve uma data atípica, com um número elevado de sinistros,
# possivelmente devido a um evento específico,
# como um feriado prolongado ou condições climáticas adversas.

epoca_sinistros = pd.read_sql_query('''SELECT count(id) AS total_sinistros, data_inversa FROM
 tb_acidentes GROUP BY data_inversa ORDER BY total_sinistros DESC;''', conexao)

epoca_sinistros.head(5)

   total_sinistros data_inversa
0              319   2024-12-21
1              303   2023-12-23
2              285   2025-12-20
3              282   2024-10-20
4              281   2025-12-12

In [97]:

conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')
pd.read_sql_query('''SELECT name from sqlite_master WHERE type='table';''', conexao)

                 name
0        tb_acidentes
1  tb_acidentes_bruto
2  tb_acidentes_limpo

In [98]:
conexao = sqlite3.connect('2_banco_de_dados/prf_database.db')
pd.read_sql_query('''SELECT * from tb_acidentes LIMIT 5;''', conexao)

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,496519.0,2023-01-01,domingo,02:00:00,ES,101,114,SOORETAMA,Ausência de reação do condutor,Saída de leito carroçável,...,0,0,0,1,1,"-19,09484877","-40,05095848",SPRF-ES,DEL04-ES,UOP01-DEL04-ES
1,496543.0,2023-01-01,domingo,03:40:00,SP,116,"113,1",TAUBATE,Entrada inopinada do pedestre,Atropelamento de Pedestre,...,0,0,4,0,2,"-23,0445658","-45,58259814",SPRF-SP,DEL02-SP,UOP02-DEL02-SP
2,496590.0,2023-01-01,domingo,01:40:00,MT,163,1112,GUARANTA DO NORTE,Reação tardia ou ineficiente do condutor,Tombamento,...,1,0,2,1,3,"-9,70020602","-54,87588757",SPRF-MT,DEL06-MT,UOP03-DEL06-MT
3,496610.0,2023-01-01,domingo,10:40:00,PR,376,"314,8",ORTIGUEIRA,Velocidade Incompatível,Tombamento,...,0,1,2,0,3,"-23,985512","-51,083555",SPRF-PR,DEL07-PR,UOP02-DEL07-PR
4,496659.0,2023-01-01,domingo,14:55:00,MG,116,"569,4",MANHUACU,Acumulo de água sobre o pavimento,Colisão frontal,...,2,1,1,2,3,"-20,10007457","-42,17884091",SPRF-MG,DEL06-MG,UOP03-DEL06-MG

In [99]:
pd.read_sql_query("""
    SELECT
        'tb_acidentes_bruto' AS tabela,
        COUNT(*) AS registros
    FROM tb_acidentes_bruto

    UNION ALL

    SELECT
        'tb_acidentes_limpo' AS tabela,
        COUNT(*) AS registros
    FROM tb_acidentes_limpo

    UNION ALL

    SELECT
        'tb_acidentes' AS tabela,
        COUNT(*) AS registros
    FROM tb_acidentes;
""", conexao)

               tabela  registros
0  tb_acidentes_bruto     243225
1  tb_acidentes_limpo     243225
2        tb_acidentes     243225

In [102]:
# Exportar a tabela tratada para utilização no Power BI

dados_finais = pd.read_sql_query("""
    SELECT *
    FROM tb_acidentes
""", conexao)

dados_finais.to_csv(
    "3_dados_finais/acidentes_tratados.csv",
    index=False,
    encoding="utf-8-sig"
)

print(f"Arquivo exportado com {len(dados_finais):,} registros.")

Arquivo exportado com 243,225 registros.